### PR TITLE
Improve packaging, 3.18.1, complete python3 and apparmor support

### PR DESCRIPTION
**Pull request by cpaelzer**
Hi,
I started working through lintian errors, but while I was working on it I realized that I could just as well do much more. Therefore I also completed an apparmor profile I was working on a while ago, continued the effort you started with python3 support and moved to 3.18.1.

You'll need a fixed Scons to build it as-is, I have one available at [PPA](https://launchpad.net/~ci-train-ppa-service/+archive/ubuntu/3507/+packages) which is based on this [PR](https://salsa.debian.org/debian/scons/merge_requests/1) implementing your suggestion.
I have asked a few people to consider to NMU bug [893740](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893740) so I hope that is soon unblocked.

I realized this branch collected quite some commits, so waiting for scons might be just the time you need to actually review all of them.

Let me know if you'd want something discussed or modified - on irc I'm `cpaelzer` and on most `#ubuntu-*` Freenode channels, but also at `#debian` on OFTC.

### CODE REVIEW

**Comment by cpaelzer** [comment]
FYI - I still see this and I'm not sure if it is a 3.18.1 bug or something in my non-gps device system.

    gpsd:ERROR: shmget(0x47505344, 14024, 0666) for SHM export failed: Invalid argument

In general I tested as much as I could, but lacking a matching device that was rather theoretical.
I hope that all the minor and major improvements still help you to make a great 3.18.1 upload.

**Comment by bzed** [comment]
You should have an collab invite to this repository, makes things easier.

Please also push the upstream/pristine tar branches. Thanks a lot!

**Comment by cpaelzer** [comment]
On Fri, Nov 9, 2018 at 5:38 PM Bernd Zeimetz <notifications@github.com> wrote:
>
> You should have an collab invite to this repository, makes things easier.

Got it, thanks!

>
> Please also push the upstream/pristine tar branches. Thanks a lot!


To github.com:bzed/pkg-gpsd.git
  69729839..70c3c947  pristine-tar -> pristine-tar
To github.com:bzed/pkg-gpsd.git
  fe63bf31..83796219  upstream-3.18.1 -> upstream

Both uploaded and ready for you

Also the scons fixes were uploaded, so I think everything falls into
place and it should hopefully work now.
Maybe you can give it a try with some real devices first? Because that
was what I could not do.

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Christian Ehrhardt
Software Engineer, Ubuntu Server
Canonical Ltd

**Comment by bzed** [comment]
@cpaelzer hmm, fails to build in a clean chroot here :(

**Comment by bzed** [comment]
(not?) Building in travis again: https://travis-ci.org/bzed/pkg-gpsd/builds/455731662

actually I'm thinking about moving the packaging to salsa.debian.org as the CI pipelines there are much better than travis.

**Comment by cpaelzer** [comment]
Odd, I built it[ here](https://launchpad.net/~ci-train-ppa-service/+archive/ubuntu/3507/+packages) with the updated Scons which now is in Debian as well.

Let me take a look at the errors you see ...

**Comment by cpaelzer** [comment]
Hmm, the fail is about systemctl in the tests.
Maybe base dependencies are slightly different for that in Ubuntu/Debian. I'll spin up an autopkgtest Debian instance later today and take a look - I'm glad the actual build worked, we surely can sort out the test as well. Just need to handle a few other things this morning before I get to it.

**Comment by cpaelzer** [comment]
Looking deeper I'm actually more concerned about these:
gpsd-clients: missing-dep-for-interpreter python2 => python:any | python-minimal:any | python2:any | python2-minimal:any
...
dpkg-gencontrol: warning: package python-gps: substitution variable ${python:Versions} unused, but is defined

Didn't realize and of those before - I'll need a full Debian-sid build env to be sure on all of this.
I certainly didn't want to cause more work for you, I'll ping you once I got to it ...

**Comment by cpaelzer** [comment]
@bzed hi I've taken a look and it is something of the last few days only.
I already have a few fixes and opened PR #2 so that we can discuss details of the current build there.

**Pull request merged**
